### ISSUE TITLE
Confusion wrt README

### ISSUE THREAD

**Issue by vchong** [KYVENetwork/ksync#1]
https://github.com/KYVENetwork/ksync/blob/main/README.md says:
For P2P-SYNC:
Make sure that persistent_peers are empty
Make sure that your addrbook.json is empty or delete it entirely
```
pex = false
allow_duplicate_ip = true
```

For DB-SYNC:
```
# config.toml
proxy_app = "tcp://127.0.0.1:26658"
abci = "socket"
```

So far so good, but then the "Sync Osmosis with DB-SYNC" example says:
"Don't include an addrbook.json and make sure persistent_peers and etc. are empty" -> 1. based on above, these are settings for P2P-SYNC, not DB-SYNC. Are they needed for DB-SYNC too?
2. Also, what do `and etc.` refer to? The `pex` and `allow_duplicate_ip` settings? The `proxy_app` and `abci` settings? Other settings like unconditional peers, private peers, etc?

3. Is a list of pool IDs for the networks available somewhere?

Thanks

**Comment by christopherbrumm** [comment]
1. To actually use only the blocks validated and archived through KYVE, you need to make sure your node connects to any other peers in the actual network. Therefore, it's important to remove the `addrbook.json` and `persistent_peers` using both versions, P2P and DB-SYNC.
2. This refers to other ways to connect to peers in the network, e.g. `seeds`. With the default config including no added peers you should use DB-SYNC without problems.
3. Not yet, but I'll add a ticket to create a map of pools with all supported products and docs on how to use them. Right now, there is just the Cosmos Hub pool on Mainnet, which you can see [here](https://app.kyve.network/#/pools). On our Testnet Kaon, you can already find an Osmosis pool [here](https://app.kaon.kyve.network/#/pools).

**Comment by christopherbrumm** [comment]
We'll definitely updating the README regarding this indistinctness.

Thank you very much!
