### ISSUE TITLE
KSync drop IPv6 brackets ( [ ] )

### ISSUE THREAD

**Issue by Galadrin** [KYVENetwork/ksync#9]
When using IPv6 in node configuration, Ksync fail to setup the P2P listening addresses.
The call to the method `Hostname()` drop the brackets mandatory around IPv6 addresses.

https://github.com/KYVENetwork/ksync/blob/d7c027986ba6884241a2591ea310b5a2d74dff9f/executors/blocksync/p2p/p2p.go#L148

## actual result
```
ERR [KSYNC] failed to bootstrap node: failed to start p2p executor: failed to start transport: invalid address (2a01:xxx:yyy:zzz::1:26655): address 2a01:xxx:yyy:zzz::1:26655: too many colons in address module=serve-snapshots
```
## expected result
Ksync successfully connect to `[2a01:xxx:yyy:zzz::1]:26655`

**Comment by troykessler** [comment]
Thank you for submitting! We will check asap on how to tix this
